# Generated by Django 2.0.3 on 2019-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('brief', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': '基金',
                'verbose_name_plural': '基金',
            },
        ),
    ]
