# Generated by Django 2.0.3 on 2019-04-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('funds', '0002_auto_20190419_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.User'),
        ),
        migrations.AddField(
            model_name='fundlog',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Fund'),
        ),
    ]
