# Generated by Django 2.0.3 on 2019-04-19 15:37

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0002_auto_20190419_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=256)),
                ('concerned_funds', jsonfield.fields.JSONField(default=list, verbose_name='关注的基金代码')),
            ],
        ),
        migrations.CreateModel(
            name='UserFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='持有份额')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.User')),
            ],
            options={
                'verbose_name': '用户持有基金',
                'verbose_name_plural': '用户持有基金',
            },
        ),
    ]
